"""Añadido campo leido a la tabla Mensajeria

Revision ID: 5eb11a2b1438
Revises: 
Create Date: 2025-08-24 17:35:05.218799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eb11a2b1438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leido', sa.Boolean(), nullable=False))
        batch_op.alter_column('id_emisor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_receptor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajeria', schema=None) as batch_op:
        batch_op.alter_column('id_receptor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_emisor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('leido')

    # ### end Alembic commands ###
